version: '3.9'

services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:  ${DB_NAME}
    container_name: employeesnttdata
    volumes:
      - ./postgres:/var/lib/postgresql/employeenttdata